### ISSUE TITLE
`synvert-ruby -q rails` doesn't work

### ISSUE THREAD

**Issue by bibendi** [xinminlabs/synvert-ruby#104]
An instance variable `@options` doesn't initialised in `Command` class https://github.com/xinminlabs/synvert-ruby/blob/669a9b8752d12d3dbfc9c6d6a60edbee397e2a28/lib/synvert/command.rb#L82

**Comment by flyerhzm** [comment]
@bibendi I have fixed it and released version 1.9.0

**Comment by bibendi** [comment]
Thank you!
