### ISSUE TITLE
unary splat operator is not handled properly

### ISSUE THREAD

**Issue by riffraff** [xinminlabs/synvert-ruby#30]
I have seen this with the rails/strong_parameters snippet, but I think the problem is more general.

Basically, given a source like

```
attr_accessible *args
```

doing

```
eval arguments.first.to_source # "*args"
```

is never going to do the right thing, because `eval("*args")`is invalid.
This can't be handled easily because the splat operator needs to bubble up the chain of calls, but replacing `eval` with an appropriate `synvert_eval` may allow the tool to work while notifying the users, i.e.

```
def synvert_eval token, expr, file, line 
   if token[0] == ?*
      log "synvert could not handle #{expr} at #{file}:#{line}, look for SYNVERT_FIXME to handle this"
      "SYNVERT_FIXME('#{token}',#{file},#{line})"
   else
      eval(token)
   end
end
```

**Comment by flyerhzm** [comment]
closed as it's outdated
